// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: '1:111771436235:web:124f27000c7a046394874e',
    messagingSenderId: '111771436235',
    projectId: 'tripbudget-8515a',
    authDomain: 'tripbudget-8515a.firebaseapp.com',
    storageBucket: 'tripbudget-8515a.appspot.com',
    measurementId: 'G-Q9M5Y0ZT95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: '1:111771436235:android:1014bd3aa7cdeadc94874e',
    messagingSenderId: '111771436235',
    projectId: 'tripbudget-8515a',
    storageBucket: 'tripbudget-8515a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: '1:111771436235:ios:4ee7d9247218078994874e',
    messagingSenderId: '111771436235',
    projectId: 'tripbudget-8515a',
    storageBucket: 'tripbudget-8515a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: '1:111771436235:ios:4ee7d9247218078994874e',
    messagingSenderId: '111771436235',
    projectId: 'tripbudget-8515a',
    storageBucket: 'tripbudget-8515a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: '1:111771436235:web:49622d752d5e810d94874e',
    messagingSenderId: '111771436235',
    projectId: 'tripbudget-8515a',
    authDomain: 'tripbudget-8515a.firebaseapp.com',
    storageBucket: 'tripbudget-8515a.appspot.com',
    measurementId: 'G-T88PJPELH2',
  );
}
